name: Laravel

on:
  push:
    branches: [ "test-action" ]
  pull_request:
    branches: [ "test-action" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: pipeline
          MYSQL_ROOT_PASSWORD: forge
          DB_HOST: 127.0.0.1
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Run npm ci
      run: npm ci
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Build site
      run: npm run dev
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Migrate MySQL DB
      env: 
        DB_CONNECTION: mysql
        DB_DATABASE: pipeline
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: forge
      run: php artisan migrate:fresh --seed
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        browser: chrome
        install: false
        start: npm start
        wait-on: http://localhost:8000
        config-file: cypress.js
        spec: tests/cypress/e2e/integration/*
        env: CYPRESS_BASE_URL=http://127.0.0.1:8000
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
